**Data Cleaning & Preparation**

In [2]:
import pandas as pd

df = pd.read_csv("IPL.csv")

# Display first five rows
df.head()

/tmp/ipykernel_3798/3644005991.py:3: DtypeWarning: Columns (20,32,43,46,47,48,51,64) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("IPL.csv")

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982.0,2008-04-18,T20,Indian Premier League,1.0,Kolkata Knight Riders,Royal Challengers Bangalore,0.0,1.0,...,1.0,0.0,NaN,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982.0,2008-04-18,T20,Indian Premier League,1.0,Kolkata Knight Riders,Royal Challengers Bangalore,0.0,2.0,...,2.0,0.0,NaN,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982.0,2008-04-18,T20,Indian Premier League,1.0,Kolkata Knight Riders,Royal Challengers Bangalore,0.0,3.0,...,2.0,0.0,NaN,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982.0,2008-04-18,T20,Indian Premier League,1.0,Kolkata Knight Riders,Royal Challengers Bangalore,0.0,3.0,...,3.0,0.0,NaN,NaN,0.0,2.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982.0,2008-04-18,T20,Indian Premier League,1.0,Kolkata Knight Riders,Royal Challengers Bangalore,0.0,4.0,...,4.0,0.0,NaN,NaN,0.0,3.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [8]:
df.info()

df.describe()

df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30371 entries, 0 to 30370
Data columns (total 65 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         30371 non-null  int64
 1   match_id           30370 non-null  float64
 2   date               30370 non-null  object
 3   match_type         30370 non-null  object
 4   event_name         30370 non-null  object
 5   innings            30370 non-null  float64
 6   batting_team       30370 non-null  object
 7   bowling_team       30370 non-null  object
 8   over               30370 non-null  float64
 9   ball               30370 non-null  float64
 10  ball_no            30370 non-null  float64
 11  batter             30370 non-null  object
 12  bat_pos            30370 non-null  float64
 13  runs_batter        30370 non-null  float64
 14  balls_faced        30370 non-null  float64
 15  bowler             30370 non-null  object
 16  valid_ball         30370 non-null  float64
 17  runs_extras        30370 non-null  float64
 18  runs_total         30370 non-null  float64
 19  runs_bowler        30370 non-null  float64
 20  runs_not_boundary  30370 non-null  object
 21  extra_type         1860 non-null   object
 22  non_striker        30370 non-null  object
 23  non_striker_pos    30370 non-null  float64
 24  wicket_kind        1552 non-null   object
 25  player_out         1552 non-null   object
 26  fielders           1131 non-null   object
 27  runs_target        14519 non-null  float64
 28  review_batter      0 non-null      float64
 29  team_reviewed      0 non-null      float64
 30  review_decision    0 non-null      float64
 31  umpire             0 non-null      float64
 32  umpires_call       30370 non-null  object
 33  player_of_match    30370 non-null  object
 34  match_won_by       30370 non-null  object
 35  win_outcome        30103 non-null  object
 36  toss_winner        30370 non-null  object
 37  toss_decision      30370 non-null  object
 38  venue              30370 non-null  object
 39  city               30370 non-null  object
 40  day                30370 non-null  float64
 41  month              30370 non-null  float64
 42  year               30370 non-null  float64
 43  season             30370 non-null  object
 44  gender             30370 non-null  object
 45  team_type          30370 non-null  object
 46  superover_winner   267 non-null    object
 47  result_type        267 non-null    object
 48  method             813 non-null    object
 49  balls_per_over     30370 non-null  float64
 50  overs              30370 non-null  float64
 51  event_match_no     30370 non-null  object
 52  stage              30370 non-null  object
 53  match_number       30370 non-null  object
 54  team_runs          30370 non-null  float64
 55  team_balls         30370 non-null  float64
 56  team_wicket        30370 non-null  float64
 57  new_batter         1496 non-null   object
 58  power_surge_start  0 non-null      float64
 59  batter_runs        30370 non-null  float64
 60  batter_balls       30370 non-null  float64
 61  bowler_wicket      30370 non-null  float64
 62  batting_partners   30370 non-null  object
 63  next_batter        1496 non-null   object
 64  striker_out        30370 non-null  object
dtypes: float64(30), int64(1), object(34)
memory usage: 15.1+ MB

(30371, 65)

In [7]:
df.isnull().sum()

Unnamed: 0              0
match_id                1
date                    1
match_type              1
event_name              1
                    ...
batter_balls            1
bowler_wicket           1
batting_partners        1
next_batter         28875
striker_out             1
Length: 65, dtype: int64

In [9]:
# Remove the unnecessary index column
df.drop(columns=['Unnamed: 0'], inplace=True)
text_cols = [
    'extra_type',
    'wicket_kind',
    'player_out',
    'fielders',
    'review_batter',
    'team_reviewed',
    'review_decision',
    'superover_winner',
    'result_type',
    'method',
    'new_batter',
    'next_batter'
]

#Fill missing categorical values with "Not Applicable"
for col in text_cols:
    df[col] = df[col].fillna("Not Applicable")
numeric_cols = [
    'team_runs',
    'team_balls',
    'team_wicket',
    'batter_runs',
    'batter_balls',
    'bowler_wicket'
]

for col in numeric_cols:
    df[col] = df[col].fillna(0)
#the column contains no useful information Drop it
df.drop(columns=['power_surge_start'], inplace=True)

In [10]:
text_columns = [
    'match_type', 'event_name', 'batting_team', 'bowling_team',
    'batter', 'bowler', 'extra_type', 'non_striker',
    'wicket_kind', 'player_out', 'fielders',
    'review_batter', 'team_reviewed', 'review_decision',
    'player_of_match', 'match_won_by', 'win_outcome',
    'toss_winner', 'toss_decision', 'venue', 'city',
    'season', 'gender', 'team_type', 'superover_winner',
    'result_type', 'method', 'event_match_no', 'stage',
    'match_number', 'new_batter', 'next_batter', 'striker_out'
]

for col in text_columns:
    if col in df.columns:
        df[col] = df[col].fillna("Not Applicable").astype(str).str.strip().str.title()

In [11]:
# Convert the date column to datetime format.
df['date'] = pd.to_datetime(df['date'])

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.rename(columns={
    'runs_batter':'batter_runs_scored',
    'runs_total':'total_runs',
    'runs_bowler':'bowler_runs'
}, inplace=True)

In [17]:
 #Create a new column to classify deliveries as boundaries or non-boundaries.
 df['Boundary'] = df['batter_runs_scored'].apply(
    lambda x: 'Boundary' if x in [4,6] else 'Other'
)

In [18]:
df.to_csv("cleaned_dataset.csv", index=False)